-- =============================================================================
-- SmartKüche — Supabase / PostgreSQL Database Schema
-- =============================================================================
-- Stack  : Supabase (PostgreSQL 15+), Frankfurt region (eu-central-1)
-- Auth   : Supabase Auth (auth.users is the identity source of truth)
-- RLS    : Enabled on every table; no public access
-- Realtime: Enabled on shopping_list_items
-- Prices : Stored as EUR cents (integer) throughout
-- Locale : All content strings are German
-- =============================================================================

-- ---------------------------------------------------------------------------
-- EXTENSIONS
-- ---------------------------------------------------------------------------

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";      -- uuid_generate_v4()
CREATE EXTENSION IF NOT EXISTS "pg_trgm";        -- trigram indexes for full-text search
CREATE EXTENSION IF NOT EXISTS "unaccent";       -- accent-insensitive German search


-- =============================================================================
-- ENUM TYPES
-- =============================================================================

-- Supported German grocery store chains
CREATE TYPE preferred_store_enum AS ENUM (
  'REWE',
  'EDEKA',
  'Lidl',
  'Aldi',
  'Kaufland',
  'Other'
);

-- Dietary lifestyle
CREATE TYPE diet_type_enum AS ENUM (
  'omnivor',        -- alles
  'flexitarisch',   -- wenig Fleisch
  'vegetarisch',    -- kein Fleisch/Fisch
  'vegan',          -- keine tierischen Produkte
  'pescetarisch'    -- Fisch, aber kein Fleisch
);

-- Shopping budget mode
CREATE TYPE budget_mode_enum AS ENUM (
  'normal',
  'sparwoche'       -- strict budget week
);

-- German supermarket aisle / ingredient category
CREATE TYPE ingredient_category_enum AS ENUM (
  'Obst & Gemüse',
  'Fleisch & Wurst',
  'Milchprodukte',
  'Kühlregal',
  'Tiefkühl',
  'Konserven & Gläser',
  'Backzutaten',
  'Gewürze & Öle',
  'Getränke',
  'Brot & Backwaren',
  'Süßwaren & Snacks',
  'Sonstiges'
);

-- Standard metric + German packaging units
CREATE TYPE unit_enum AS ENUM (
  'g',
  'kg',
  'ml',
  'l',
  'Stück',
  'Bund',
  'Packung',
  'Dose',
  'Becher',
  'Tüte'
);

-- Where an ingredient is stored at home
CREATE TYPE storage_type_enum AS ENUM (
  'Kühlschrank',
  'Tiefkühler',
  'Vorratskammer',
  'Raumtemperatur'
);

-- Recipe difficulty
CREATE TYPE difficulty_enum AS ENUM (
  'einfach',
  'mittel',
  'anspruchsvoll'
);

-- Rough cost classification per serving
CREATE TYPE cost_rating_enum AS ENUM (
  'günstig',
  'mittel',
  'gehoben'
);

-- Meal plan lifecycle state
CREATE TYPE meal_plan_status_enum AS ENUM (
  'draft',
  'active',
  'completed'
);

-- Shopping list lifecycle state
CREATE TYPE shopping_list_status_enum AS ENUM (
  'draft',
  'shopping',
  'completed'
);


-- =============================================================================
-- HELPER: updated_at TRIGGER FUNCTION
-- =============================================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;


-- =============================================================================
-- TABLE: households
-- =============================================================================
-- A household is a group of users who share meal plans and shopping lists.
-- Created before the user profile because users.household_id references it.

CREATE TABLE IF NOT EXISTS households (
  id            UUID          PRIMARY KEY DEFAULT uuid_generate_v4(),
  name          TEXT          NOT NULL,
  size          INTEGER       NOT NULL DEFAULT 1 CHECK (size BETWEEN 1 AND 20),
  created_by    UUID          NOT NULL REFERENCES auth.users (id) ON DELETE SET NULL,
  invite_code   TEXT          NOT NULL UNIQUE,  -- 6-char alphanumeric, generated by Edge Function
  created_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  households              IS 'A group of users sharing meal plans and shopping lists.';
COMMENT ON COLUMN households.size         IS 'Total number of people in the household (used for portion scaling).';
COMMENT ON COLUMN households.invite_code  IS '6-character alphanumeric code used to invite other users to this household.';
COMMENT ON COLUMN households.created_by   IS 'The user who originally created this household (household owner).';

CREATE TRIGGER households_updated_at
  BEFORE UPDATE ON households
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Indexes
CREATE INDEX IF NOT EXISTS idx_households_invite_code ON households (invite_code);
CREATE INDEX IF NOT EXISTS idx_households_created_by  ON households (created_by);


-- =============================================================================
-- TABLE: users  (extends auth.users)
-- =============================================================================
-- One row per Supabase auth user. Inserted automatically via trigger on
-- auth.users INSERT (or manually after sign-up).

CREATE TABLE IF NOT EXISTS users (
  id                    UUID                  PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  display_name          TEXT,
  household_id          UUID                  REFERENCES households (id) ON DELETE SET NULL,
  preferred_store       preferred_store_enum  NOT NULL DEFAULT 'REWE',
  onboarding_completed  BOOLEAN               NOT NULL DEFAULT FALSE,
  created_at            TIMESTAMPTZ           NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ           NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  users                       IS 'App-level user profile that extends the Supabase auth.users identity.';
COMMENT ON COLUMN users.id                    IS 'Mirrors auth.users.id — the Supabase Auth UUID.';
COMMENT ON COLUMN users.household_id          IS 'The household this user currently belongs to (nullable until household is joined or created).';
COMMENT ON COLUMN users.preferred_store       IS 'The preferred supermarket chain; affects aisle sorting and package-size rounding.';
COMMENT ON COLUMN users.onboarding_completed  IS 'Set to TRUE once the user completes all onboarding screens.';

CREATE TRIGGER users_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Indexes
CREATE INDEX IF NOT EXISTS idx_users_household_id ON users (household_id);

-- Auto-create a users row when a new auth.users row is inserted
CREATE OR REPLACE FUNCTION handle_new_auth_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO public.users (id)
  VALUES (NEW.id)
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION handle_new_auth_user();


-- =============================================================================
-- TABLE: user_preferences
-- =============================================================================
-- Diet and budget configuration per user. Written during onboarding, updateable
-- at any time from the settings screen.

CREATE TABLE IF NOT EXISTS user_preferences (
  user_id                   UUID              PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
  diet_type                 diet_type_enum    NOT NULL DEFAULT 'omnivor',
  allergies                 TEXT[]            NOT NULL DEFAULT '{}',
  excluded_ingredients      TEXT[]            NOT NULL DEFAULT '{}',
  max_cooking_time_minutes  INTEGER           CHECK (max_cooking_time_minutes > 0),
  budget_mode               budget_mode_enum  NOT NULL DEFAULT 'normal',
  weekly_budget_cents       INTEGER           CHECK (weekly_budget_cents IS NULL OR weekly_budget_cents > 0),
  updated_at                TIMESTAMPTZ       NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  user_preferences                        IS 'Dietary, allergy, and budget preferences for a single user. One row per user.';
COMMENT ON COLUMN user_preferences.allergies              IS 'Array of allergen keys, e.g. ARRAY[''Laktose'', ''Gluten'', ''Nüsse'']. Used to filter incompatible recipes.';
COMMENT ON COLUMN user_preferences.excluded_ingredients   IS 'Free-text ingredient names the user wants to avoid (beyond strict allergens).';
COMMENT ON COLUMN user_preferences.max_cooking_time_minutes IS 'Upper bound on prep+cook time the user is willing to spend per day. NULL = unbegrenzt.';
COMMENT ON COLUMN user_preferences.weekly_budget_cents    IS 'Optional weekly grocery budget in EUR cents. NULL if not set. Only relevant when budget_mode = ''sparwoche''.';

CREATE TRIGGER user_preferences_updated_at
  BEFORE UPDATE ON user_preferences
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- =============================================================================
-- TABLE: ingredients
-- =============================================================================
-- Master catalogue of purchasable ingredients. Admin-managed.

CREATE TABLE IF NOT EXISTS ingredients (
  id                    UUID                      PRIMARY KEY DEFAULT uuid_generate_v4(),
  name_de               TEXT                      NOT NULL,
  category              ingredient_category_enum  NOT NULL,
  default_unit          unit_enum                 NOT NULL,
  common_package_sizes  JSONB                     NOT NULL DEFAULT '{}',
  shelf_life_days       INTEGER                   CHECK (shelf_life_days IS NULL OR shelf_life_days > 0),
  storage_type          storage_type_enum         NOT NULL DEFAULT 'Raumtemperatur',
  is_seasonal           BOOLEAN                   NOT NULL DEFAULT FALSE,
  season_months         INTEGER[]                 NOT NULL DEFAULT '{}',  -- 1 = January … 12 = December
  created_at            TIMESTAMPTZ               NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ               NOT NULL DEFAULT NOW(),

  CONSTRAINT season_months_valid CHECK (
    season_months <@ ARRAY[1,2,3,4,5,6,7,8,9,10,11,12]::INTEGER[]
  )
);

COMMENT ON TABLE  ingredients                       IS 'Master catalogue of purchasable ingredients. Admin-managed; referenced by recipes and shopping list items.';
COMMENT ON COLUMN ingredients.name_de               IS 'German ingredient name, e.g. "Vollmilch", "Hackfleisch", "Weizenmehl Type 405".';
COMMENT ON COLUMN ingredients.common_package_sizes  IS 'JSONB map of package sizes by store, e.g. {"REWE": [500, 1000], "Lidl": [1000]}. Values are in the ingredient''s default_unit.';
COMMENT ON COLUMN ingredients.shelf_life_days       IS 'Typical shelf life in days from purchase. NULL if highly variable.';
COMMENT ON COLUMN ingredients.is_seasonal           IS 'TRUE if this ingredient has a notable seasonal availability (e.g. Spargel, Erdbeeren).';
COMMENT ON COLUMN ingredients.season_months         IS 'Months (1–12) when this ingredient is in season. Empty array if is_seasonal = FALSE.';

CREATE TRIGGER ingredients_updated_at
  BEFORE UPDATE ON ingredients
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Indexes
CREATE INDEX IF NOT EXISTS idx_ingredients_category     ON ingredients (category);
CREATE INDEX IF NOT EXISTS idx_ingredients_name_de_trgm ON ingredients USING gin (name_de gin_trgm_ops);


-- =============================================================================
-- TABLE: recipes
-- =============================================================================
-- Core content table. Admin-managed; users can read but not write.

CREATE TABLE IF NOT EXISTS recipes (
  id                              UUID              PRIMARY KEY DEFAULT uuid_generate_v4(),
  title_de                        TEXT              NOT NULL,
  description_de                  TEXT,
  instructions_de                 JSONB             NOT NULL DEFAULT '[]',  -- ordered array of step strings
  prep_time_minutes               INTEGER           NOT NULL DEFAULT 0 CHECK (prep_time_minutes >= 0),
  cook_time_minutes               INTEGER           NOT NULL DEFAULT 0 CHECK (cook_time_minutes >= 0),
  difficulty                      difficulty_enum   NOT NULL DEFAULT 'einfach',
  servings_default                INTEGER           NOT NULL DEFAULT 4 CHECK (servings_default BETWEEN 1 AND 20),
  meal_type                       TEXT[]            NOT NULL DEFAULT '{}',  -- e.g. ARRAY['Mittagessen', 'Abendessen']
  diet_tags                       TEXT[]            NOT NULL DEFAULT '{}',  -- e.g. ARRAY['vegetarisch', 'vegan']
  cost_rating                     cost_rating_enum  NOT NULL DEFAULT 'mittel',
  cost_estimate_cents_per_serving INTEGER           CHECK (cost_estimate_cents_per_serving IS NULL OR cost_estimate_cents_per_serving > 0),
  image_url                       TEXT,
  source_attribution              TEXT,
  is_seasonal                     BOOLEAN           NOT NULL DEFAULT FALSE,
  season_months                   INTEGER[]         NOT NULL DEFAULT '{}',
  created_at                      TIMESTAMPTZ       NOT NULL DEFAULT NOW(),
  updated_at                      TIMESTAMPTZ       NOT NULL DEFAULT NOW(),

  -- Full-text search vector (German language config, updated via trigger below)
  fts_de  TSVECTOR GENERATED ALWAYS AS (
    to_tsvector('german', coalesce(title_de, '') || ' ' || coalesce(description_de, ''))
  ) STORED,

  CONSTRAINT season_months_valid CHECK (
    season_months <@ ARRAY[1,2,3,4,5,6,7,8,9,10,11,12]::INTEGER[]
  )
);

COMMENT ON TABLE  recipes                               IS 'Core recipe catalogue in German. Admin-managed. All text is in German.';
COMMENT ON COLUMN recipes.instructions_de               IS 'Ordered JSONB array of instruction step strings, e.g. ["Zwiebeln würfeln.", "Hackfleisch anbraten.", ...]';
COMMENT ON COLUMN recipes.meal_type                     IS 'Which meals this recipe suits, e.g. ARRAY[''Frühstück'', ''Mittagessen'', ''Abendessen'', ''Abendbrot'']. Abendbrot is first-class.';
COMMENT ON COLUMN recipes.diet_tags                     IS 'Diet types this recipe is compatible with, e.g. ARRAY[''vegetarisch'', ''vegan''].';
COMMENT ON COLUMN recipes.cost_estimate_cents_per_serving IS 'Rough ingredient cost per serving in EUR cents (e.g. 250 = €2,50). Used to filter by budget.';
COMMENT ON COLUMN recipes.source_attribution            IS 'Optional attribution string if recipe originates from an external source.';
COMMENT ON COLUMN recipes.fts_de                        IS 'Generated tsvector for German full-text search across title and description.';

CREATE TRIGGER recipes_updated_at
  BEFORE UPDATE ON recipes
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Indexes
CREATE INDEX IF NOT EXISTS idx_recipes_fts_de        ON recipes USING gin (fts_de);
CREATE INDEX IF NOT EXISTS idx_recipes_meal_type      ON recipes USING gin (meal_type);
CREATE INDEX IF NOT EXISTS idx_recipes_diet_tags      ON recipes USING gin (diet_tags);
CREATE INDEX IF NOT EXISTS idx_recipes_difficulty     ON recipes (difficulty);
CREATE INDEX IF NOT EXISTS idx_recipes_cost_rating    ON recipes (cost_rating);
CREATE INDEX IF NOT EXISTS idx_recipes_is_seasonal    ON recipes (is_seasonal);
CREATE INDEX IF NOT EXISTS idx_recipes_total_time     ON recipes ((prep_time_minutes + cook_time_minutes));


-- =============================================================================
-- TABLE: recipe_ingredients
-- =============================================================================
-- Junction table linking recipes to their required ingredients, with amounts.

CREATE TABLE IF NOT EXISTS recipe_ingredients (
  id                UUID      PRIMARY KEY DEFAULT uuid_generate_v4(),
  recipe_id         UUID      NOT NULL REFERENCES recipes (id) ON DELETE CASCADE,
  ingredient_id     UUID      NOT NULL REFERENCES ingredients (id) ON DELETE RESTRICT,
  amount            NUMERIC   NOT NULL CHECK (amount > 0),
  unit              TEXT      NOT NULL,  -- stored as text to allow recipe-specific overrides
  preparation_note  TEXT,               -- e.g. "fein gehackt", "in Würfel geschnitten"

  UNIQUE (recipe_id, ingredient_id)     -- one entry per ingredient per recipe; use amount for multiples
);

COMMENT ON TABLE  recipe_ingredients                   IS 'Links each recipe to its required ingredients with amounts and optional preparation notes.';
COMMENT ON COLUMN recipe_ingredients.unit              IS 'Unit for this specific recipe-ingredient combination. May differ from ingredients.default_unit (e.g. a recipe uses ml where the ingredient default is l).';
COMMENT ON COLUMN recipe_ingredients.preparation_note  IS 'German preparation instruction for this ingredient in this recipe, e.g. "fein gehackt", "in Scheiben geschnitten".';

-- Indexes
CREATE INDEX IF NOT EXISTS idx_recipe_ingredients_recipe_id     ON recipe_ingredients (recipe_id);
CREATE INDEX IF NOT EXISTS idx_recipe_ingredients_ingredient_id ON recipe_ingredients (ingredient_id);


-- =============================================================================
-- TABLE: meal_plans
-- =============================================================================
-- A 7-day meal plan belonging to a household. Generated by the Edge Function.

CREATE TABLE IF NOT EXISTS meal_plans (
  id              UUID                    PRIMARY KEY DEFAULT uuid_generate_v4(),
  household_id    UUID                    NOT NULL REFERENCES households (id) ON DELETE CASCADE,
  created_by      UUID                    NOT NULL REFERENCES users (id) ON DELETE SET NULL,
  week_start_date DATE                    NOT NULL,  -- always a Monday (enforced by app logic)
  status          meal_plan_status_enum   NOT NULL DEFAULT 'draft',
  created_at      TIMESTAMPTZ             NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ             NOT NULL DEFAULT NOW(),

  -- At most one active plan per household per week
  UNIQUE (household_id, week_start_date)
);

COMMENT ON TABLE  meal_plans                   IS 'A 7-day meal plan for a household. Each plan covers exactly one calendar week.';
COMMENT ON COLUMN meal_plans.week_start_date   IS 'The Monday of the planned week (ISO date). Enforced as Monday by the generate-plan Edge Function.';
COMMENT ON COLUMN meal_plans.status            IS 'draft = being assembled; active = the current week''s plan; completed = past week.';

CREATE TRIGGER meal_plans_updated_at
  BEFORE UPDATE ON meal_plans
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Indexes
CREATE INDEX IF NOT EXISTS idx_meal_plans_household_id    ON meal_plans (household_id);
CREATE INDEX IF NOT EXISTS idx_meal_plans_week_start_date ON meal_plans (week_start_date);
CREATE INDEX IF NOT EXISTS idx_meal_plans_status          ON meal_plans (status);


-- =============================================================================
-- TABLE: meal_slots
-- =============================================================================
-- Each row is one meal within a meal plan (day × meal type × recipe).

CREATE TABLE IF NOT EXISTS meal_slots (
  id                UUID      PRIMARY KEY DEFAULT uuid_generate_v4(),
  meal_plan_id      UUID      NOT NULL REFERENCES meal_plans (id) ON DELETE CASCADE,
  day_of_week       SMALLINT  NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),  -- 0 = Monday
  meal_type         TEXT      NOT NULL,  -- 'Frühstück' | 'Mittagessen' | 'Abendessen' | 'Abendbrot'
  recipe_id         UUID      REFERENCES recipes (id) ON DELETE SET NULL,    -- NULL = slot intentionally empty
  is_locked         BOOLEAN   NOT NULL DEFAULT FALSE,
  servings_override SMALLINT  CHECK (servings_override IS NULL OR servings_override BETWEEN 1 AND 20),
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Each (plan, day, meal_type) combination is unique
  UNIQUE (meal_plan_id, day_of_week, meal_type)
);

COMMENT ON TABLE  meal_slots                    IS 'Individual meal slots within a meal plan. One row per (plan, day, meal type) combination.';
COMMENT ON COLUMN meal_slots.day_of_week        IS '0 = Monday, 1 = Tuesday, …, 6 = Sunday.';
COMMENT ON COLUMN meal_slots.meal_type          IS 'One of: Frühstück, Mittagessen, Abendessen, Abendbrot. Abendbrot is a distinct cold-dinner type.';
COMMENT ON COLUMN meal_slots.is_locked          IS 'When TRUE, the regenerate-plan algorithm skips this slot and keeps the assigned recipe.';
COMMENT ON COLUMN meal_slots.servings_override  IS 'If set, overrides the recipe''s servings_default for this slot. NULL = use household size from preferences.';

CREATE TRIGGER meal_slots_updated_at
  BEFORE UPDATE ON meal_slots
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Indexes
CREATE INDEX IF NOT EXISTS idx_meal_slots_meal_plan_id ON meal_slots (meal_plan_id);
CREATE INDEX IF NOT EXISTS idx_meal_slots_recipe_id    ON meal_slots (recipe_id);


-- =============================================================================
-- TABLE: shopping_lists
-- =============================================================================
-- One shopping list per meal plan per household. Derived by the Edge Function.

CREATE TABLE IF NOT EXISTS shopping_lists (
  id            UUID                        PRIMARY KEY DEFAULT uuid_generate_v4(),
  meal_plan_id  UUID                        NOT NULL REFERENCES meal_plans (id) ON DELETE CASCADE,
  household_id  UUID                        NOT NULL REFERENCES households (id) ON DELETE CASCADE,
  status        shopping_list_status_enum   NOT NULL DEFAULT 'draft',
  created_at    TIMESTAMPTZ                 NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ                 NOT NULL DEFAULT NOW(),

  -- One shopping list per meal plan
  UNIQUE (meal_plan_id)
);

COMMENT ON TABLE  shopping_lists              IS 'Aggregated shopping list derived from a meal plan. Shared across all members of a household.';
COMMENT ON COLUMN shopping_lists.status       IS 'draft = list not yet finalized; shopping = actively being used in the store; completed = shopping trip done.';
COMMENT ON COLUMN shopping_lists.household_id IS 'Denormalized from meal_plans.household_id for efficient RLS lookups.';

CREATE TRIGGER shopping_lists_updated_at
  BEFORE UPDATE ON shopping_lists
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Indexes
CREATE INDEX IF NOT EXISTS idx_shopping_lists_meal_plan_id  ON shopping_lists (meal_plan_id);
CREATE INDEX IF NOT EXISTS idx_shopping_lists_household_id  ON shopping_lists (household_id);
CREATE INDEX IF NOT EXISTS idx_shopping_lists_status        ON shopping_lists (status);


-- =============================================================================
-- TABLE: shopping_list_items
-- =============================================================================
-- Individual line items on a shopping list. This table is Realtime-enabled
-- so household members see checkboxes update in real time.

CREATE TABLE IF NOT EXISTS shopping_list_items (
  id                UUID          PRIMARY KEY DEFAULT uuid_generate_v4(),
  shopping_list_id  UUID          NOT NULL REFERENCES shopping_lists (id) ON DELETE CASCADE,
  ingredient_id     UUID          REFERENCES ingredients (id) ON DELETE SET NULL,
  amount_needed     NUMERIC       NOT NULL CHECK (amount_needed > 0),
  unit              TEXT          NOT NULL,
  display_text      TEXT          NOT NULL,  -- German, e.g. "Vollmilch (1 Packung, 1 l)"
  aisle_category    TEXT          NOT NULL,  -- matches AisleCategory in the TypeScript client
  is_checked        BOOLEAN       NOT NULL DEFAULT FALSE,
  checked_by        UUID          REFERENCES users (id) ON DELETE SET NULL,
  checked_at        TIMESTAMPTZ,
  created_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  shopping_list_items                 IS 'Individual items on a shopping list. Realtime-enabled for live household sync.';
COMMENT ON COLUMN shopping_list_items.display_text    IS 'Human-readable German label shown in the app, e.g. "Butter (2 × 250 g)".';
COMMENT ON COLUMN shopping_list_items.aisle_category  IS 'German supermarket aisle category used to group and sort items, matching the AisleCategory TypeScript enum.';
COMMENT ON COLUMN shopping_list_items.is_checked      IS 'TRUE once a household member has checked this item off in the store.';
COMMENT ON COLUMN shopping_list_items.checked_by      IS 'User ID of the household member who checked off this item. NULL if not yet checked.';
COMMENT ON COLUMN shopping_list_items.checked_at      IS 'Timestamp of when the item was checked off. Used for audit and conflict resolution (last-write-wins).';

CREATE TRIGGER shopping_list_items_updated_at
  BEFORE UPDATE ON shopping_list_items
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Indexes
CREATE INDEX IF NOT EXISTS idx_shopping_list_items_shopping_list_id ON shopping_list_items (shopping_list_id);
CREATE INDEX IF NOT EXISTS idx_shopping_list_items_ingredient_id    ON shopping_list_items (ingredient_id);
CREATE INDEX IF NOT EXISTS idx_shopping_list_items_is_checked       ON shopping_list_items (shopping_list_id, is_checked);
CREATE INDEX IF NOT EXISTS idx_shopping_list_items_aisle_category   ON shopping_list_items (shopping_list_id, aisle_category);

-- ---------------------------------------------------------------------------
-- REALTIME: enable on shopping_list_items
-- ---------------------------------------------------------------------------
-- Allows the Supabase Realtime server to broadcast row changes (INSERT /
-- UPDATE / DELETE) to subscribed clients over WebSocket.
-- Clients subscribe via: supabase.channel('shopping-list:<listId>')
--   .on('postgres_changes', { event: '*', table: 'shopping_list_items', filter: 'shopping_list_id=eq.<id>' }, ...)

ALTER PUBLICATION supabase_realtime ADD TABLE shopping_list_items;


-- =============================================================================
-- PHASE 2 TABLE: pantry_items
-- =============================================================================
-- Tracks current ingredient inventory per household.
-- Not exposed in Phase 1 UI but included in the initial migration so no
-- schema migration is needed when the Pantry feature ships.

CREATE TABLE IF NOT EXISTS pantry_items (
  id             UUID          PRIMARY KEY DEFAULT uuid_generate_v4(),
  household_id   UUID          NOT NULL REFERENCES households (id) ON DELETE CASCADE,
  ingredient_id  UUID          NOT NULL REFERENCES ingredients (id) ON DELETE RESTRICT,
  amount         NUMERIC       NOT NULL CHECK (amount > 0),
  unit           TEXT          NOT NULL,
  expires_at     DATE,
  added_by       UUID          NOT NULL REFERENCES users (id) ON DELETE SET NULL,
  created_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  pantry_items             IS 'Phase 2: Household pantry inventory. Informs meal plan generation (prefer recipes that use expiring items).';
COMMENT ON COLUMN pantry_items.expires_at  IS 'Optional expiry date. The generate-plan algorithm prioritises recipes that consume items expiring soon.';

CREATE TRIGGER pantry_items_updated_at
  BEFORE UPDATE ON pantry_items
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Indexes
CREATE INDEX IF NOT EXISTS idx_pantry_items_household_id  ON pantry_items (household_id);
CREATE INDEX IF NOT EXISTS idx_pantry_items_expires_at    ON pantry_items (household_id, expires_at);


-- =============================================================================
-- ROW LEVEL SECURITY
-- =============================================================================
-- Strategy:
--   • Recipes and ingredients are readable by all authenticated users.
--   • Admin-only writes on recipes / ingredients via JWT claim check.
--   • All household data (plans, lists, pantry) is scoped to household members.
--   • User rows and preferences are only accessible by the owning user.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- RLS: households
-- ---------------------------------------------------------------------------

ALTER TABLE households ENABLE ROW LEVEL SECURITY;

-- Any authenticated user can see a household they belong to
CREATE POLICY "households_select_member"
  ON households FOR SELECT
  USING (
    id IN (
      SELECT household_id FROM users
      WHERE users.id = auth.uid()
    )
  );

-- Any authenticated user can create a new household (they become its owner)
CREATE POLICY "households_insert_authenticated"
  ON households FOR INSERT
  WITH CHECK (auth.uid() = created_by);

-- Only the household creator (owner) can update household details
CREATE POLICY "households_update_owner"
  ON households FOR UPDATE
  USING (created_by = auth.uid())
  WITH CHECK (created_by = auth.uid());

-- Only the household creator can delete it
CREATE POLICY "households_delete_owner"
  ON households FOR DELETE
  USING (created_by = auth.uid());


-- ---------------------------------------------------------------------------
-- RLS: users
-- ---------------------------------------------------------------------------

ALTER TABLE users ENABLE ROW LEVEL SECURITY;

-- Users can see their own profile
CREATE POLICY "users_select_self"
  ON users FOR SELECT
  USING (id = auth.uid());

-- Users in the same household can see each other's display_name (for "checked_by" attribution)
CREATE POLICY "users_select_same_household"
  ON users FOR SELECT
  USING (
    household_id IS NOT NULL
    AND household_id = (
      SELECT household_id FROM users AS me WHERE me.id = auth.uid()
    )
  );

-- Users can only update their own profile
CREATE POLICY "users_update_self"
  ON users FOR UPDATE
  USING (id = auth.uid())
  WITH CHECK (id = auth.uid());

-- Row is inserted automatically by the on_auth_user_created trigger (SECURITY DEFINER)
-- No manual INSERT policy needed for regular users.


-- ---------------------------------------------------------------------------
-- RLS: user_preferences
-- ---------------------------------------------------------------------------

ALTER TABLE user_preferences ENABLE ROW LEVEL SECURITY;

-- Users can only read their own preferences
CREATE POLICY "user_preferences_select_self"
  ON user_preferences FOR SELECT
  USING (user_id = auth.uid());

-- Users can insert their own preferences
CREATE POLICY "user_preferences_insert_self"
  ON user_preferences FOR INSERT
  WITH CHECK (user_id = auth.uid());

-- Users can update only their own preferences
CREATE POLICY "user_preferences_update_self"
  ON user_preferences FOR UPDATE
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- Users can delete their own preferences (e.g. account deletion flow)
CREATE POLICY "user_preferences_delete_self"
  ON user_preferences FOR DELETE
  USING (user_id = auth.uid());


-- ---------------------------------------------------------------------------
-- RLS: ingredients
-- ---------------------------------------------------------------------------

ALTER TABLE ingredients ENABLE ROW LEVEL SECURITY;

-- All authenticated users can read the ingredient catalogue
CREATE POLICY "ingredients_select_authenticated"
  ON ingredients FOR SELECT
  USING (auth.role() = 'authenticated');

-- Only admins can create, update, or delete ingredients
CREATE POLICY "ingredients_insert_admin"
  ON ingredients FOR INSERT
  WITH CHECK ((auth.jwt() ->> 'user_role') = 'admin');

CREATE POLICY "ingredients_update_admin"
  ON ingredients FOR UPDATE
  USING ((auth.jwt() ->> 'user_role') = 'admin')
  WITH CHECK ((auth.jwt() ->> 'user_role') = 'admin');

CREATE POLICY "ingredients_delete_admin"
  ON ingredients FOR DELETE
  USING ((auth.jwt() ->> 'user_role') = 'admin');


-- ---------------------------------------------------------------------------
-- RLS: recipes
-- ---------------------------------------------------------------------------

ALTER TABLE recipes ENABLE ROW LEVEL SECURITY;

-- All authenticated users can read recipes
CREATE POLICY "recipes_select_authenticated"
  ON recipes FOR SELECT
  USING (auth.role() = 'authenticated');

-- Only admins can create recipes
CREATE POLICY "recipes_insert_admin"
  ON recipes FOR INSERT
  WITH CHECK ((auth.jwt() ->> 'user_role') = 'admin');

-- Only admins can update recipes
CREATE POLICY "recipes_update_admin"
  ON recipes FOR UPDATE
  USING ((auth.jwt() ->> 'user_role') = 'admin')
  WITH CHECK ((auth.jwt() ->> 'user_role') = 'admin');

-- Only admins can delete recipes
CREATE POLICY "recipes_delete_admin"
  ON recipes FOR DELETE
  USING ((auth.jwt() ->> 'user_role') = 'admin');


-- ---------------------------------------------------------------------------
-- RLS: recipe_ingredients
-- ---------------------------------------------------------------------------

ALTER TABLE recipe_ingredients ENABLE ROW LEVEL SECURITY;

-- All authenticated users can read recipe ingredients
CREATE POLICY "recipe_ingredients_select_authenticated"
  ON recipe_ingredients FOR SELECT
  USING (auth.role() = 'authenticated');

-- Only admins can write recipe ingredients
CREATE POLICY "recipe_ingredients_insert_admin"
  ON recipe_ingredients FOR INSERT
  WITH CHECK ((auth.jwt() ->> 'user_role') = 'admin');

CREATE POLICY "recipe_ingredients_update_admin"
  ON recipe_ingredients FOR UPDATE
  USING ((auth.jwt() ->> 'user_role') = 'admin')
  WITH CHECK ((auth.jwt() ->> 'user_role') = 'admin');

CREATE POLICY "recipe_ingredients_delete_admin"
  ON recipe_ingredients FOR DELETE
  USING ((auth.jwt() ->> 'user_role') = 'admin');


-- ---------------------------------------------------------------------------
-- RLS: meal_plans
-- ---------------------------------------------------------------------------

ALTER TABLE meal_plans ENABLE ROW LEVEL SECURITY;

-- Household members can see their household's plans
CREATE POLICY "meal_plans_select_household_member"
  ON meal_plans FOR SELECT
  USING (
    household_id = (
      SELECT household_id FROM users WHERE users.id = auth.uid()
    )
  );

-- Any household member can create a plan for their household
CREATE POLICY "meal_plans_insert_household_member"
  ON meal_plans FOR INSERT
  WITH CHECK (
    household_id = (
      SELECT household_id FROM users WHERE users.id = auth.uid()
    )
    AND created_by = auth.uid()
  );

-- Any household member can update a plan
CREATE POLICY "meal_plans_update_household_member"
  ON meal_plans FOR UPDATE
  USING (
    household_id = (
      SELECT household_id FROM users WHERE users.id = auth.uid()
    )
  )
  WITH CHECK (
    household_id = (
      SELECT household_id FROM users WHERE users.id = auth.uid()
    )
  );

-- Only the plan creator can delete a plan
CREATE POLICY "meal_plans_delete_creator"
  ON meal_plans FOR DELETE
  USING (created_by = auth.uid());


-- ---------------------------------------------------------------------------
-- RLS: meal_slots
-- ---------------------------------------------------------------------------

ALTER TABLE meal_slots ENABLE ROW LEVEL SECURITY;

-- Helper: is the requesting user a member of the household that owns this plan?
CREATE POLICY "meal_slots_select_household_member"
  ON meal_slots FOR SELECT
  USING (
    meal_plan_id IN (
      SELECT id FROM meal_plans
      WHERE household_id = (
        SELECT household_id FROM users WHERE users.id = auth.uid()
      )
    )
  );

CREATE POLICY "meal_slots_insert_household_member"
  ON meal_slots FOR INSERT
  WITH CHECK (
    meal_plan_id IN (
      SELECT id FROM meal_plans
      WHERE household_id = (
        SELECT household_id FROM users WHERE users.id = auth.uid()
      )
    )
  );

CREATE POLICY "meal_slots_update_household_member"
  ON meal_slots FOR UPDATE
  USING (
    meal_plan_id IN (
      SELECT id FROM meal_plans
      WHERE household_id = (
        SELECT household_id FROM users WHERE users.id = auth.uid()
      )
    )
  )
  WITH CHECK (
    meal_plan_id IN (
      SELECT id FROM meal_plans
      WHERE household_id = (
        SELECT household_id FROM users WHERE users.id = auth.uid()
      )
    )
  );

CREATE POLICY "meal_slots_delete_household_member"
  ON meal_slots FOR DELETE
  USING (
    meal_plan_id IN (
      SELECT id FROM meal_plans
      WHERE household_id = (
        SELECT household_id FROM users WHERE users.id = auth.uid()
      )
    )
  );


-- ---------------------------------------------------------------------------
-- RLS: shopping_lists
-- ---------------------------------------------------------------------------

ALTER TABLE shopping_lists ENABLE ROW LEVEL SECURITY;

-- Household members can see their household's shopping lists
CREATE POLICY "shopping_lists_select_household_member"
  ON shopping_lists FOR SELECT
  USING (
    household_id = (
      SELECT household_id FROM users WHERE users.id = auth.uid()
    )
  );

-- Any household member can create a shopping list for their household
CREATE POLICY "shopping_lists_insert_household_member"
  ON shopping_lists FOR INSERT
  WITH CHECK (
    household_id = (
      SELECT household_id FROM users WHERE users.id = auth.uid()
    )
  );

-- Any household member can update the list status
CREATE POLICY "shopping_lists_update_household_member"
  ON shopping_lists FOR UPDATE
  USING (
    household_id = (
      SELECT household_id FROM users WHERE users.id = auth.uid()
    )
  )
  WITH CHECK (
    household_id = (
      SELECT household_id FROM users WHERE users.id = auth.uid()
    )
  );

-- Any household member can delete the shopping list
CREATE POLICY "shopping_lists_delete_household_member"
  ON shopping_lists FOR DELETE
  USING (
    household_id = (
      SELECT household_id FROM users WHERE users.id = auth.uid()
    )
  );


-- ---------------------------------------------------------------------------
-- RLS: shopping_list_items
-- ---------------------------------------------------------------------------

ALTER TABLE shopping_list_items ENABLE ROW LEVEL SECURITY;

-- Household members can read items belonging to their household's lists
CREATE POLICY "shopping_list_items_select_household_member"
  ON shopping_list_items FOR SELECT
  USING (
    shopping_list_id IN (
      SELECT id FROM shopping_lists
      WHERE household_id = (
        SELECT household_id FROM users WHERE users.id = auth.uid()
      )
    )
  );

-- Any household member can add items to their household's list
CREATE POLICY "shopping_list_items_insert_household_member"
  ON shopping_list_items FOR INSERT
  WITH CHECK (
    shopping_list_id IN (
      SELECT id FROM shopping_lists
      WHERE household_id = (
        SELECT household_id FROM users WHERE users.id = auth.uid()
      )
    )
  );

-- Any household member can update items (e.g. check off) on their household's list
CREATE POLICY "shopping_list_items_update_household_member"
  ON shopping_list_items FOR UPDATE
  USING (
    shopping_list_id IN (
      SELECT id FROM shopping_lists
      WHERE household_id = (
        SELECT household_id FROM users WHERE users.id = auth.uid()
      )
    )
  )
  WITH CHECK (
    shopping_list_id IN (
      SELECT id FROM shopping_lists
      WHERE household_id = (
        SELECT household_id FROM users WHERE users.id = auth.uid()
      )
    )
  );

-- Any household member can delete items from their household's list
CREATE POLICY "shopping_list_items_delete_household_member"
  ON shopping_list_items FOR DELETE
  USING (
    shopping_list_id IN (
      SELECT id FROM shopping_lists
      WHERE household_id = (
        SELECT household_id FROM users WHERE users.id = auth.uid()
      )
    )
  );


-- ---------------------------------------------------------------------------
-- RLS: pantry_items  (Phase 2)
-- ---------------------------------------------------------------------------

ALTER TABLE pantry_items ENABLE ROW LEVEL SECURITY;

-- Household members can see their household's pantry
CREATE POLICY "pantry_items_select_household_member"
  ON pantry_items FOR SELECT
  USING (
    household_id = (
      SELECT household_id FROM users WHERE users.id = auth.uid()
    )
  );

-- Any household member can add to the pantry
CREATE POLICY "pantry_items_insert_household_member"
  ON pantry_items FOR INSERT
  WITH CHECK (
    household_id = (
      SELECT household_id FROM users WHERE users.id = auth.uid()
    )
    AND added_by = auth.uid()
  );

-- Any household member can update pantry items (adjust amount, update expiry)
CREATE POLICY "pantry_items_update_household_member"
  ON pantry_items FOR UPDATE
  USING (
    household_id = (
      SELECT household_id FROM users WHERE users.id = auth.uid()
    )
  )
  WITH CHECK (
    household_id = (
      SELECT household_id FROM users WHERE users.id = auth.uid()
    )
  );

-- Any household member can remove a pantry item
CREATE POLICY "pantry_items_delete_household_member"
  ON pantry_items FOR DELETE
  USING (
    household_id = (
      SELECT household_id FROM users WHERE users.id = auth.uid()
    )
  );


-- =============================================================================
-- SEED: Example data for local development
-- =============================================================================
-- Remove this section before deploying to production.
-- Run: psql -c "\i database-schema.sql" to apply, then insert dev data separately.
-- =============================================================================

-- (No seed data included — add to a separate supabase/seed.sql file.)


-- =============================================================================
-- END OF SCHEMA
-- =============================================================================
